# Generated by Django 5.1.6 on 2025-04-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=50)),
                ('paymentStatus', models.CharField(max_length=50)),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('transactionId', models.CharField(max_length=100)),
            ],
        ),
    ]
