# Generated by Django 5.1.6 on 2025-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=100)),
                ('adminRole', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
