import pandas as pd

# Tạo dữ liệu giả lập với 200 bình luận (100 tích cực, 100 tiêu cực)
data = {
    "content": [
        # 100 bình luận tích cực
        "Sản phẩm này rất tốt tôi rất hài lòng!",
        "Chất lượng tuyệt vời giao hàng nhanh!",
        "Mua lần thứ 2 rồi vẫn ưng ý như lần đầu!",
        "Đẹp bền giá cả hợp lý đáng mua!",
        "Dịch vụ chăm sóc khách hàng rất chu đáo!",
        "Sản phẩm dùng rất ổn tôi sẽ giới thiệu cho bạn bè!",
        "Màu sắc đẹp thiết kế sang trọng rất thích!",
        "Giao hàng đúng hẹn đóng gói cẩn thận!",
        "Giá cả phải chăng chất lượng vượt mong đợi!",
        "Rất hài lòng với trải nghiệm mua sắm này!",
        "Sản phẩm đúng như mô tả không thất vọng!",
        "Dùng một thời gian rồi vẫn rất tốt!",
        "Shop tư vấn nhiệt tình sản phẩm chất lượng!",
        "Mua cho gia đình dùng ai cũng khen!",
        "Hàng chính hãng đáng đồng tiền bát gạo!",
        "Thiết kế hiện đại rất phù hợp với nhu cầu của tôi!",
        "Sản phẩm này xứng đáng 5 sao!",
        "Giao hàng siêu nhanh cảm ơn shop nhiều!",
        "Chất lượng tốt tôi sẽ tiếp tục ủng hộ shop!",
        "Mua lần đầu mà ấn tượng quá tuyệt vời!",
        "Sản phẩm bền dùng lâu mà không hỏng!",
        "Giá rẻ mà chất lượng rất đáng mua!",
        "Shop phục vụ tốt sản phẩm không có gì để chê!",
        "Hàng đẹp đúng như hình rất ưng ý!",
        "Dùng sản phẩm này thấy tiện lợi hơn hẳn!",
        "Mua làm quà tặng người nhận rất thích!",
        "Sản phẩm này giúp tôi tiết kiệm thời gian rất nhiều!",
        "Chất liệu tốt cảm giác cao cấp khi sử dụng!",
        "Shop giao hàng nhanh thái độ phục vụ tốt!",
        "Sản phẩm này đúng là lựa chọn hoàn hảo!",
        "Tôi rất thích cách shop chăm sóc khách hàng!",
        "Hàng đẹp giá hợp lý sẽ mua thêm!",
        "Sản phẩm này làm tôi hài lòng hơn mong đợi!",
        "Dùng thử thấy rất ổn sẽ giới thiệu cho mọi người!",
        "Giao hàng nhanh sản phẩm đúng như quảng cáo!",
        "Chất lượng tốt giá cả hợp lý rất đáng tiền!",
        "Sản phẩm này giúp cuộc sống của tôi dễ dàng hơn!",
        "Shop uy tín sản phẩm chất lượng cao!",
        "Mua lần này rất ưng sẽ quay lại lần sau!",
        "Sản phẩm đẹp đóng gói kỹ càng rất hài lòng!",
        "Dịch vụ tốt sản phẩm xài ổn 5 sao!",
        "Hàng đẹp chất lượng tôi rất thích!",
        "Sản phẩm này đúng là tuyệt vời không chê được!",
        "Shop giao hàng nhanh sản phẩm đúng mô tả!",
        "Chất lượng sản phẩm vượt trội rất đáng mua!",
        "Mua về dùng thử thấy rất tốt sẽ ủng hộ tiếp!",
        "Sản phẩm này làm tôi rất hài lòng cảm ơn shop!",
        "Hàng đẹp giá rẻ dịch vụ tốt tuyệt vời!",
        "Sản phẩm chất lượng tôi rất ưng ý!",
        "Shop tư vấn nhiệt tình sản phẩm dùng rất tốt!",
        "Mua lần đầu mà đã thích sẽ mua thêm nữa!",
        "Sản phẩm này đáng giá từng đồng rất hài lòng!",
        "Giao hàng nhanh đóng gói cẩn thận sản phẩm tốt!",
        "Chất lượng sản phẩm tốt tôi rất thích!",
        "Shop phục vụ chu đáo sản phẩm chất lượng cao!",
        "Sản phẩm này rất tiện lợi tôi rất ưng!",
        "Hàng đẹp giá cả hợp lý sẽ ủng hộ shop dài dài!",
        "Sản phẩm này làm tôi rất hài lòng tuyệt!",
        "Dùng sản phẩm này thấy rất ổn không thất vọng!",
        "Shop giao hàng nhanh sản phẩm chất lượng 5 sao!",
        "Sản phẩm đẹp bền giá cả hợp lý rất đáng mua!",
        "Dịch vụ chăm sóc khách hàng tốt sản phẩm ổn!",
        "Sản phẩm này rất tốt tôi sẽ giới thiệu cho bạn bè!",
        "Màu sắc đẹp thiết kế sang trọng rất hài lòng!",
        "Giao hàng đúng hẹn đóng gói cẩn thận sản phẩm tốt!",
        "Giá cả phải chăng chất lượng vượt mong đợi tuyệt!",
        "Rất hài lòng với trải nghiệm mua sắm này 5 sao!",
        "Sản phẩm đúng như mô tả không thất vọng rất tốt!",
        "Dùng một thời gian rồi vẫn rất tốt đáng mua!",
        "Shop tư vấn nhiệt tình sản phẩm chất lượng tuyệt vời!",
        "Mua cho gia đình dùng ai cũng khen rất ưng!",
        "Hàng chính hãng đáng đồng tiền tôi rất hài lòng!",
        "Thiết kế hiện đại rất phù hợp với nhu cầu của tôi!",
        "Sản phẩm này xứng đáng 5 sao rất tuyệt!",
        "Giao hàng siêu nhanh cảm ơn shop nhiều sản phẩm tốt!",
        "Chất lượng tốt tôi sẽ tiếp tục ủng hộ shop rất ưng!",
        "Mua lần đầu mà ấn tượng quá sản phẩm tuyệt vời!",
        "Sản phẩm bền dùng lâu mà không hỏng rất đáng mua!",
        "Giá rẻ mà chất lượng rất đáng mua tôi rất thích!",
        "Shop phục vụ tốt sản phẩm không có gì để chê tuyệt!",
        "Hàng đẹp đúng như hình rất ưng ý cảm ơn shop!",
        "Dùng sản phẩm này thấy tiện lợi hơn hẳn rất tốt!",
        "Mua làm quà tặng người nhận rất thích rất hài lòng!",
        "Sản phẩm này giúp tôi tiết kiệm thời gian rất nhiều!",
        "Chất liệu tốt cảm giác cao cấp khi sử dụng rất ưng!",
        "Shop giao hàng nhanh thái độ phục vụ tốt sản phẩm ổn!",
        "Sản phẩm này đúng là lựa chọn hoàn hảo rất tuyệt!",
        "Tôi rất thích cách shop chăm sóc khách hàng sản phẩm tốt!",
        "Hàng đẹp giá hợp lý sẽ mua thêm rất hài lòng!",
        "Sản phẩm này làm tôi hài lòng hơn mong đợi rất ưng!",
        "Dùng thử thấy rất ổn sẽ giới thiệu cho mọi người!",
        "Giao hàng nhanh sản phẩm đúng như quảng cáo rất tốt!",
        "Chất lượng tốt giá cả hợp lý rất đáng tiền tuyệt!",
        "Sản phẩm này giúp cuộc sống của tôi dễ dàng hơn rất ưng!",
        "Shop uy tín sản phẩm chất lượng cao rất hài lòng!",
        "Mua lần này rất ưng sẽ quay lại lần sau sản phẩm tốt!",
        "Sản phẩm đẹp đóng gói kỹ càng rất hài lòng 5 sao!",
        "Sách đọc hay vãi chưởng",
        "Tuyệt lắm, mua thêm 100 lần nữa",
        "Quá hay!"

        # 100 bình luận tiêu cực
        "Sản phẩm tệ không như quảng cáo rất thất vọng!",
        "Giao hàng chậm thái độ nhân viên kém không hài lòng!",
        "Hàng lỗi không dùng được thất vọng quá!",
        "Giá cao mà chất lượng không tương xứng không đáng mua!",
        "Mua về dùng 1 lần là hỏng quá tệ không hài lòng!",
        "Sản phẩm không giống hình cảm giác bị lừa!",
        "Giao hàng trễ đóng gói ẩu sản phẩm bị hỏng!",
        "Chất lượng kém dùng vài ngày đã hỏng thất vọng!",
        "Shop không uy tín sản phẩm không đúng mô tả!",
        "Dịch vụ chăm sóc khách hàng tệ không giải quyết vấn đề!",
        "Sản phẩm này không đáng tiền rất thất vọng!",
        "Hàng giả không chính hãng cảm giác bị lừa!",
        "Giao hàng chậm sản phẩm lỗi không hài lòng!",
        "Sản phẩm kém chất lượng không như kỳ vọng!",
        "Mua về mà không dùng được quá thất vọng!",
        "Giá đắt mà chất lượng kém không đáng mua!",
        "Shop giao sai sản phẩm thái độ phục vụ tệ!",
        "Sản phẩm này không bền dùng vài lần là hỏng!",
        "Hàng không đúng mô tả rất thất vọng không mua nữa!",
        "Dịch vụ giao hàng tệ sản phẩm bị móp méo!",
        "Sản phẩm này không tốt tôi rất thất vọng!",
        "Mua về mà không dùng được cảm giác phí tiền!",
        "Shop không hỗ trợ đổi trả sản phẩm lỗi rất tệ!",
        "Hàng kém chất lượng không như quảng cáo thất vọng!",
        "Giao hàng chậm sản phẩm không đúng không hài lòng!",
        "Sản phẩm này quá tệ không đáng mua rất thất vọng!",
        "Chất lượng kém giá lại cao không đáng tiền!",
        "Shop giao hàng chậm sản phẩm lỗi không hài lòng!",
        "Sản phẩm không giống hình rất thất vọng không mua nữa!",
        "Dịch vụ tệ sản phẩm kém không đáng để mua!",
        "Sản phẩm này không bền dùng vài ngày là hỏng thất vọng!",
        "Hàng không đúng mô tả cảm giác bị lừa rất tệ!",
        "Giao hàng chậm sản phẩm bị hỏng không hài lòng!",
        "Sản phẩm kém chất lượng không như kỳ vọng thất vọng!",
        "Mua về mà không dùng được quá thất vọng không mua nữa!",
        "Giá đắt mà chất lượng kém không đáng mua rất tệ!",
        "Shop giao sai sản phẩm thái độ phục vụ tệ không hài lòng!",
        "Sản phẩm này không bền dùng vài lần là hỏng thất vọng!",
        "Hàng không đúng mô tả rất thất vọng không mua nữa!",
        "Dịch vụ giao hàng tệ sản phẩm bị móp méo không hài lòng!",
        "Sản phẩm này không tốt tôi rất thất vọng không mua nữa!",
        "Mua về mà không dùng được cảm giác phí tiền rất tệ!",
        "Shop không hỗ trợ đổi trả sản phẩm lỗi rất thất vọng!",
        "Hàng kém chất lượng không như quảng cáo không hài lòng!",
        "Giao hàng chậm sản phẩm không đúng rất thất vọng!",
        "Sản phẩm này quá tệ không đáng mua không hài lòng!",
        "Chất lượng kém giá lại cao không đáng tiền thất vọng!",
        "Shop giao hàng chậm sản phẩm lỗi không hài lòng rất tệ!",
        "Sản phẩm không giống hình rất thất vọng không mua nữa!",
        "Dịch vụ tệ sản phẩm kém không đáng để mua thất vọng!",
        "Sản phẩm này không bền dùng vài ngày là hỏng không hài lòng!",
        "Hàng không đúng mô tả cảm giác bị lừa rất thất vọng!",
        "Giao hàng chậm sản phẩm bị hỏng không hài lòng rất tệ!",
        "Sản phẩm kém chất lượng không như kỳ vọng không mua nữa!",
        "Mua về mà không dùng được quá thất vọng rất thất vọng!",
        "Giá đắt mà chất lượng kém không đáng mua không hài lòng!",
        "Shop giao sai sản phẩm thái độ phục vụ tệ rất thất vọng!",
        "Sản phẩm này không bền dùng vài lần là hỏng không hài lòng!",
        "Hàng không đúng mô tả rất thất vọng không mua nữa rất tệ!",
        "Dịch vụ giao hàng tệ sản phẩm bị móp méo không hài lòng!",
        "Sản phẩm này không tốt tôi rất thất vọng không mua nữa!",
        "Mua về mà không dùng được cảm giác phí tiền rất thất vọng!",
        "Shop không hỗ trợ đổi trả sản phẩm lỗi rất thất vọng không hài lòng!",
        "Hàng kém chất lượng không như quảng cáo không hài lòng rất tệ!",
        "Giao hàng chậm sản phẩm không đúng rất thất vọng không mua nữa!",
        "Sản phẩm này quá tệ không đáng mua không hài lòng rất thất vọng!",
        "Chất lượng kém giá lại cao không đáng tiền không hài lòng!",
        "Shop giao hàng chậm sản phẩm lỗi không hài lòng rất thất vọng!",
        "Sản phẩm không giống hình rất thất vọng không mua nữa không hài lòng!",
        "Dịch vụ tệ sản phẩm kém không đáng để mua rất thất vọng!",
        "Sản phẩm này không bền dùng vài ngày là hỏng không hài lòng rất tệ!",
        "Hàng không đúng mô tả cảm giác bị lừa rất thất vọng không mua nữa!",
        "Giao hàng chậm sản phẩm bị hỏng không hài lòng rất thất vọng!",
        "Sản phẩm kém chất lượng không như kỳ vọng không mua nữa rất tệ!",
        "Mua về mà không dùng được quá thất vọng rất thất vọng không hài lòng!",
        "Giá đắt mà chất lượng kém không đáng mua không hài lòng rất thất vọng!",
        "Shop giao sai sản phẩm thái độ phục vụ tệ rất thất vọng không mua nữa!",
        "Sản phẩm này không bền dùng vài lần là hỏng không hài lòng rất thất vọng!",
        "Hàng không đúng mô tả rất thất vọng không mua nữa không hài lòng rất tệ!",
        "Dịch vụ giao hàng tệ sản phẩm bị móp méo không hài lòng rất thất vọng!",
        "Sản phẩm này không tốt tôi rất thất vọng không mua nữa không hài lòng!",
        "Mua về mà không dùng được cảm giác phí tiền rất thất vọng rất tệ!",
        "Shop không hỗ trợ đổi trả sản phẩm lỗi rất thất vọng không hài lòng rất tệ!",
        "Hàng kém chất lượng không như quảng cáo không hài lòng rất thất vọng không mua nữa!",
        "Giao hàng chậm sản phẩm không đúng rất thất vọng không mua nữa không hài lòng!",
        "Sản phẩm này quá tệ không đáng mua không hài lòng rất thất vọng không mua nữa!",
        "Chất lượng kém giá lại cao không đáng tiền không hài lòng rất thất vọng rất tệ!",
        "Shop giao hàng chậm sản phẩm lỗi không hài lòng rất thất vọng không mua nữa rất tệ!",
        "Sản phẩm không giống hình rất thất vọng không mua nữa không hài lòng rất thất vọng!",
        "Dịch vụ tệ sản phẩm kém không đáng để mua rất thất vọng không mua nữa không hài lòng!",
        "Chán lắm, không thích",
        "Mất cả hứng",
        "Không được hay cho lắm, hôm sau mua shop khác",
        "Hmmmmmm, tệ lắm",
        "Đóng gói chưa được tốt cho lắm",
        "Sách bị rách",
        "Ngu lắm, không mua lại đâu",
        "Tác giả đang viết cái quái gì vậy",
        "Không hay",
        "Không được như kì vọng",
        "Không thể tin được, quá tệ"
    ],
    "label": ["tích cực"] * 100 + ["tiêu cực"] * 100  # 100 tích cực, 100 tiêu cực
}

# Kiểm tra độ dài của content và label
print(f"Số phần tử trong content: {len(data['content'])}")
print(f"Số phần tử trong label: {len(data['label'])}")

# Tạo DataFrame
df = pd.DataFrame(data)

# Lưu vào file CSV với encoding utf-8 để hỗ trợ tiếng Việt
df.to_csv("comment_data.csv", index=False, encoding="utf-8")
print("Tập dữ liệu đã được lưu vào file comment_data.csv với 200 bình luận (100 tích cực, 100 tiêu cực).")