# Generated by Django 5.1.6 on 2025-04-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
