# Generated by Django 5.1.6 on 2025-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('itemId', models.CharField(max_length=50)),
                ('customerId', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
