# Generated by Django 5.1.6 on 2025-04-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=50)),
                ('customerAddress', models.CharField(max_length=255)),
                ('shipmentStatus', models.CharField(max_length=50)),
                ('shipmentDate', models.DateField(auto_now_add=True)),
                ('estimatedDeliveryDate', models.DateField()),
                ('carrier', models.CharField(max_length=100)),
                ('trackingNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
