# Generated by Django 5.1.6 on 2025-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20250216_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=12345, max_length=255),
            preserve_default=False,
        ),
    ]
